
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 30 18:34:41 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CONST = 5;
  public static final int REM = 36;
  public static final int LOWER = 31;
  public static final int NOTEQUAL = 28;
  public static final int LPAREN = 12;
  public static final int GREATER = 29;
  public static final int SEMI = 6;
  public static final int LOWEREQUAL = 32;
  public static final int MINUS = 23;
  public static final int CHARACTER = 40;
  public static final int RPAREN = 13;
  public static final int BOOL = 39;
  public static final int COMMA = 8;
  public static final int INC = 19;
  public static final int DIV = 35;
  public static final int PLUS = 33;
  public static final int ASSIGN = 7;
  public static final int DOT = 25;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 27;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int NUMBER = 38;
  public static final int IDENT = 37;
  public static final int VOID = 14;
  public static final int GREATEREQUAL = 30;
  public static final int COLON = 22;
  public static final int LBRACE = 3;
  public static final int ENUM = 11;
  public static final int READ = 16;
  public static final int FINAL = 18;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 21;
  public static final int DEC = 20;
  public static final int PRINT = 17;
  public static final int LENGTH = 26;
}

