
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 10 15:01:16 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CHAR = 39;
  public static final int CONST = 5;
  public static final int REM = 23;
  public static final int NOTEQUAL = 25;
  public static final int LPAREN = 11;
  public static final int SEMI = 6;
  public static final int LESS = 28;
  public static final int MINUS = 20;
  public static final int RPAREN = 12;
  public static final int LESSEQUAL = 29;
  public static final int BOOL = 38;
  public static final int COMMA = 8;
  public static final int INC = 17;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int ASSIGN = 7;
  public static final int DOT = 32;
  public static final int GRATHER = 26;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 24;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int NUMBER = 37;
  public static final int IDENT = 35;
  public static final int VOID = 13;
  public static final int COLON = 31;
  public static final int LBRACE = 3;
  public static final int ENUM = 36;
  public static final int READ = 14;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 30;
  public static final int DEC = 18;
  public static final int PRINT = 15;
  public static final int LENGTH = 34;
  public static final int GRATHEREQUAL = 27;
}

